version: "3.8"

services:
  postgres:
    container_name: xenon_postgres
    build:
      context: docker
      dockerfile: database.dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql
    ports:
      - "5432:5432"

  app:
    container_name: xenon_app
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: docker/xenon.dockerfile
    ports:
      - "7000:${PORT:-7000}"
    environment:
      - "XENON_DB_HOST=postgres"
      - "XENON_LOG_CONSOLE=${LOGGING_CONSOLE:-true}"
      - "XENON_LOG_DATABASE=${LOGGING_DATABASE:-true}"
    stdin_open: true
    tty: true

volumes:
  db:
