version: "3.8"

services:
  postgres:
    container_name: xenon_postgres
    build:
      context: docker
      dockerfile: database.dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - db:/var/lib/postgresql
    ports:
      - "${DB_PORT:-5432}:5432"

  app:
    container_name: xenon_app
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: docker/xenon.dockerfile
    ports:
      - "${APP_PORT:-7000}:7000"
    environment:
      - "XENON_DB_HOST=postgres"
      - "XENON_DB_PASSWORD=${DB_PASSWORD:-postgres}"
      - "XENON_LOG_CONSOLE=${LOGGING_CONSOLE:-true}"
      - "XENON_LOG_DATABASE=${LOGGING_DATABASE:-true}"
      - "XENON_USE_SSL=${USE_SSL:-false}"
    stdin_open: true
    tty: true

volumes:
  db:
